name: Build and trigger deploy to GH Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'npm'
      - uses: dtolnay/rust-toolchain@stable

      - run: npm ci
      - run: npm i wasm-pack
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
      - run: npx nx run dicom-viewer:build-deploy --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
